"""коммит

Revision ID: d88c8bf6c046
Revises: 
Create Date: 2024-01-09 21:25:39.395383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88c8bf6c046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=False))
        batch_op.drop_constraint('vacation_week_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('user_id')
        batch_op.drop_column('week_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacation_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vacation_week_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('week')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
